version: '3.8'

services:
  stock-analysis:
    build: .
    container_name: gary_stock_analysis
    volumes:
      - ./data:/app/data  # Mount data directory
      - ./output:/app/output  # Mount output directory for images
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - DISPLAY=:99
    restart: unless-stopped
    
    # Optional: Run as cron job
    # command: >
    #   sh -c "
    #     echo '0 9 * * * cd /app && python hk_stock_analysis.py' | crontab - &&
    #     crond -f
    #   "

  # Optional: Add a web interface
  web-interface:
    build: .
    container_name: gary_stock_web
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: >
      sh -c "
        Xvfb :99 -screen 0 1920x1080x24 & 
        export DISPLAY=:99 &&
        python -m http.server 8000
      "
    environment:
      - DISPLAY=:99 